### ISSUE TITLE
未安装依赖构建失败依然提示成功

### ISSUE THREAD

**Issue by GuoYongfeng** [tinper-uba/uba-gui#2]
未安装依赖执行构建任务，出现如下信息：

![image](https://user-images.githubusercontent.com/8686869/39855859-304a8336-5460-11e8-81f4-986f6864f454.png)

**Comment by kvkens** [comment]
实际上服务端推送的消息是指任务完成，任务完成包括成功和失败，也就是我们的CURL操作完成，至于错误是webpack推回的。

后面细化错误消息类型

**Comment by kvkens** [comment]
![image](https://user-images.githubusercontent.com/3817644/40896198-4bcff778-67e6-11e8-9619-5c10d3ea0eed.png)
目前修改为命令执行完毕
